# Backend/Dockerfile.actions

FROM python:3.9-slim-bullseye

# Install dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    libpq-dev \
    curl \
    && apt-get clean

# Set working dir
WORKDIR /app

# Copy project files
COPY . /app

# Install Python deps
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Start the action server
CMD ["rasa", "run", "actions"]
