version: "3.9"

services:
  rasa:
    container_name: rasa-core
    image: rasa/rasa:3.6.2
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    working_dir: /app
    command: ["run", "--enable-api", "--cors", "*", "--debug"]
    networks:
      - rasa-net
    restart: always

  actions:
    container_name: rasa-actions
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    env_file:
      - .env
    networks:
      - rasa-net
    restart: always

networks:
  rasa-net:
    driver: bridge
