FROM python:3.9-slim-bullseye

WORKDIR /app

# Install system tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy your action server files
COPY . .

# Run the Rasa action server
CMD ["rasa", "run", "actions", "--port", "5055"]
